format = """
[┌─](bold #728c83)$username$hostname$directory$git_branch$git_status$cmd_duration
[└─>](bold #8a9a65) """

[username]
style_user = "bold #c4bcae"
style_root = "bold #c95c46"
format = "[$user]($style)@"
show_always = true

[hostname]
ssh_only = false
format = "[$hostname]($style) "
style = "bold #728c83"

[directory]
style = "bold #8a9a65"
read_only = " [RO]"
truncation_length = 3
truncate_to_repo = false
format = "[$path]($style)"

[git_branch]
style = "bold #c4a261"
symbol = " git:"
format = "[$symbol$branch]($style)"

[git_status]
style = "bold #c95c46"
format = '([ \[$all_status$ahead_behind\]]($style))'

[cmd_duration]
min_time = 1
format = " [took $duration](bold #3c3836)"
