[opener]
image = [
    { run = 'feh "$@"', orphan = true, desc = "feh" }
]
pdf = [
    { run = 'zathura "$@"', orphan = true, desc = "zathura" }
]

[open]
prepend_rules = [
        { mime = "image/*", use = "image" },
        { mime = "application/pdf", use = "pdf" }
]
