# Theme: Treated Paper
background              #121212
foreground              #dcdccc
selection_background    #3f3f3f
selection_foreground    #dcdccc

cursor                  #f0dfaf
cursor_text_color       #121212

# Standard Colors (Desaturated Retro)
color0  #121212
color1  #705050
color2  #60b48a
color3  #dfaf8f
color4  #506070
color5  #dc8cc3
color6  #8cd0d3
color7  #dcdccc
